"""empty message

Revision ID: 01304b26fb3b
Revises: 99c882a2b3d4
Create Date: 2021-06-23 18:48:15.107870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01304b26fb3b'
down_revision = '99c882a2b3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sd00_blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False, comment='JWT refresh token'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Create time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('sd10_customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=False, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False, comment='Status'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Vendor of customer'),
    sa.Column('issue_namespace', sa.String(length=50), server_default='CUSTOM-{datetime:%Y%m%d}-{serial_no:05d}', nullable=False, comment='Issue number namespace'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd10_customers_name'), 'sd10_customers', ['name'], unique=True)
    op.create_table('sd18_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='authorization role, ex: admin, user'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd30_device_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True, comment='Traffic Light part no'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Part description + specification'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd62_today_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True, comment='Time, SR+0, SS+0, 19:00'),
    sa.Column('dimming', sa.Integer(), nullable=True, comment='Dimming'),
    sa.Column('device_id', sa.Integer(), nullable=True, comment='Device_id'),
    sa.Column('incre', sa.String(length=1), nullable=True, comment='Increase Light, y/n'),
    sa.Column('vendor_device_id', sa.String(length=10), nullable=True, comment='Vender device id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd11_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='Status'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('password', sa.String(length=64), nullable=True, comment='Password'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email'),
    sa.Column('telephone', sa.String(length=30), nullable=True, comment='Telephone number'),
    sa.Column('line_id', sa.String(length=30), nullable=True, comment='LINE id'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'name')
    )
    op.create_table('sd12_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False, comment='Customer id'),
    sa.Column('code_type', sa.Integer(), nullable=True, comment='Code type, specification write in constant'),
    sa.Column('code_no', sa.Integer(), nullable=False, comment='Code number'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Code name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Code display name'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd13_user_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'name')
    )
    op.create_table('sd17_privileges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='authorization role, ex: admin, user'),
    sa.Column('api_route', sa.Text(), nullable=False, comment='API route, each api is unique'),
    sa.ForeignKeyConstraint(['role_id'], ['sd18_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd19_status_privileges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='authorization role, ex: admin, user'),
    sa.Column('status_from', sa.Integer(), nullable=True, comment='Current state'),
    sa.Column('status_to', sa.Integer(), nullable=True, comment='Next state'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sd18_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd31_controllers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='Device status flag. bit 0: warning, bit 1: error'),
    sa.Column('model_id', sa.Integer(), server_default='0', nullable=True, comment='Traffic Light model/part no'),
    sa.Column('serial_no', sa.String(length=50), nullable=False, comment='Serial No'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['sd30_device_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'name'),
    sa.UniqueConstraint('serial_no')
    )
    op.create_table('sd32_leds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='Device status flag. bit 0: warning, bit 1: error'),
    sa.Column('model_id', sa.Integer(), server_default='0', nullable=True, comment='Traffic Light model/part no'),
    sa.Column('serial_no', sa.String(length=50), nullable=False, comment='Serial No'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['sd30_device_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'name'),
    sa.UniqueConstraint('serial_no')
    )
    op.create_table('sd41_schedule_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('scheme', sa.String(length=4), nullable=True, comment='Schedule Time Scheme, 24h and srss'),
    sa.Column('incre', sa.String(length=1), nullable=True, comment='Increase Light, y/n'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'name')
    )
    op.create_table('sd52_serial_number',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False, comment='Customer id'),
    sa.Column('prefix', sa.String(length=20), nullable=False, comment='Prefix words'),
    sa.Column('serial_no', sa.Integer(), nullable=False, comment='Serial number'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'prefix', 'serial_no')
    )
    op.create_table('sd60_command',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Integer(), nullable=False, comment='Command action, 0 = dimming, 1 = power on/off'),
    sa.Column('value', sa.String(length=5), nullable=False, comment='Command value, dimming = 0~100, power = 0/1 (off/on), schedule = incre (y/n)'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('schedule_value', sa.String(length=200), nullable=True, comment='Save schedule value in json type'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd14_rel_u_ug',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_group_id'], ['sd13_user_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sd11_users.id'], )
    )
    op.create_table('sd16_rel_role_ug',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['sd18_roles.id'], ),
    sa.ForeignKeyConstraint(['user_group_id'], ['sd13_user_groups.id'], )
    )
    op.create_table('sd22_device_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.Column('schedule_id', sa.Integer(), nullable=True, comment='Schedule id, null means no schedule'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['sd41_schedule_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'name')
    )
    op.create_table('sd42_schedule_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.String(length=1), nullable=True, comment='Week Day, 0~6'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('time', sa.String(length=5), nullable=True, comment='Time, SR+0, SS+0, 19:00'),
    sa.Column('dimming', sa.Integer(), nullable=True, comment='Dimming'),
    sa.Column('schedule_group_id', sa.Integer(), nullable=True, comment='Schedule Group id'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['schedule_group_id'], ['sd41_schedule_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd15_rel_dg_ug',
    sa.Column('device_group_id', sa.Integer(), nullable=True),
    sa.Column('user_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_group_id'], ['sd22_device_groups.id'], ),
    sa.ForeignKeyConstraint(['user_group_id'], ['sd13_user_groups.id'], )
    )
    op.create_table('sd21_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True, comment='Name'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Display name'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('dev_type', sa.Integer(), server_default='0', nullable=True, comment='Device type: 0: unknown, 1: traffic light, 2: large scale devices'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.Column('vendor_id', sa.Integer(), nullable=True, comment='Vendor id'),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True, comment='Device status flag. bit 0: warning, bit 1: error'),
    sa.Column('dimming', sa.Integer(), nullable=True, comment='Device dimming. 0~100'),
    sa.Column('power_status', sa.Integer(), nullable=True, comment='Device power status. null: unknown, 0: off, 1: on'),
    sa.Column('device_group_id', sa.Integer(), nullable=True, comment='Device group id, null means ungroup'),
    sa.Column('controller_id', sa.Integer(), nullable=True, comment='Controller id'),
    sa.Column('led_id', sa.Integer(), nullable=True, comment='LED id'),
    sa.Column('vender_device_id', sa.String(length=25), nullable=True, comment='Vender device id'),
    sa.Column('wgs_x', sa.Float(), nullable=True, comment='GPS X'),
    sa.Column('wgs_y', sa.Float(), nullable=True, comment='GPS Y'),
    sa.Column('address', sa.String(length=100), nullable=True, comment='Address'),
    sa.ForeignKeyConstraint(['controller_id'], ['sd31_controllers.id'], ),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['device_group_id'], ['sd22_device_groups.id'], ),
    sa.ForeignKeyConstraint(['led_id'], ['sd32_leds.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'name')
    )
    op.create_table('sd23_device_infos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True, comment='Device id'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Comment'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('cust_id', sa.Integer(), nullable=True, comment='Customer id'),
    sa.Column('voltage', sa.Float(), nullable=True, comment='Voltage'),
    sa.Column('current', sa.Float(), nullable=True, comment='Current'),
    sa.Column('pf', sa.Float(), nullable=True, comment='Power factor'),
    sa.Column('power', sa.Float(), nullable=True, comment='Power value'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='Temperature'),
    sa.Column('lumming', sa.Float(), nullable=True, comment='Lumming'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['sd21_devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'device_id')
    )
    op.create_table('sd50_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_no', sa.String(length=30), nullable=False, comment='Issue number'),
    sa.Column('error_code', sa.Integer(), nullable=True, comment='Error code id'),
    sa.Column('priority_id', sa.Integer(), nullable=True, comment='Priority id'),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='Issue subject'),
    sa.Column('description', sa.Text(), nullable=True, comment='Issue description'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('due_day', sa.Date(), nullable=True, comment='Expected time for dispatching'),
    sa.Column('cust_id', sa.Integer(), nullable=False, comment='Customer id'),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device id'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Status id'),
    sa.Column('vendor_id', sa.Integer(), nullable=True, comment='Vendor id'),
    sa.Column('event_id', sa.Integer(), nullable=True, comment='Event log id'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='Assignee id, who is responsible for the dispatching'),
    sa.Column('report_from', sa.Integer(), nullable=False, comment='Report source'),
    sa.Column('reporter', sa.String(length=20), nullable=True, comment='Reporter name'),
    sa.Column('reporter_email', sa.String(length=100), nullable=True, comment='Reporter email'),
    sa.Column('reporter_mobile', sa.String(length=15), nullable=True, comment='Reporter mobile phone'),
    sa.Column('reporter_phone', sa.String(length=15), nullable=True, comment='Telephone telephone'),
    sa.Column('reporter_line_id', sa.String(length=64), nullable=True, comment='LINE id'),
    sa.ForeignKeyConstraint(['assignee_id'], ['sd11_users.id'], ),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['sd21_devices.id'], ),
    sa.ForeignKeyConstraint(['error_code'], ['sd12_codes.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['sd12_codes.id'], ),
    sa.ForeignKeyConstraint(['report_from'], ['sd12_codes.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['sd12_codes.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['sd10_customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_id', 'issue_no')
    )
    op.create_table('sd53_event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False, comment='Device_id'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='info, normal, warning or error'),
    sa.Column('component_id', sa.Integer(), nullable=False, comment='component of device in the event'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Event type'),
    sa.Column('description', sa.Text(), nullable=True, comment='event description'),
    sa.Column('cust_id', sa.Integer(), nullable=False, comment='Customer id'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('data_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='device data time'),
    sa.Column('replace_id', sa.Integer(), nullable=True, comment='Event id that become normal'),
    sa.Column('ack', sa.Integer(), nullable=False, comment='0 = unread, 1 = read'),
    sa.ForeignKeyConstraint(['cust_id'], ['sd10_customers.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['sd21_devices.id'], ),
    sa.ForeignKeyConstraint(['replace_id'], ['sd53_event_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd61_command_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=True, comment='Command id'),
    sa.Column('device_group_id', sa.Integer(), nullable=True, comment='Device group id'),
    sa.Column('device_id', sa.Integer(), nullable=True, comment='Device id'),
    sa.Column('status_id', sa.Integer(), nullable=False, comment='Command status'),
    sa.Column('status_changed_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.ForeignKeyConstraint(['command_id'], ['sd60_command.id'], ),
    sa.ForeignKeyConstraint(['device_group_id'], ['sd22_device_groups.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['sd21_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sd51_issue_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Sequence number of issue log'),
    sa.Column('issue_id', sa.Integer(), nullable=False, comment='Issue id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User id, who creates the issue log'),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='Issue subject'),
    sa.Column('description', sa.Text(), nullable=True, comment='Issue description'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Create time'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Update time'),
    sa.Column('status_from', sa.Integer(), nullable=False, comment='Current state'),
    sa.Column('status_to', sa.Integer(), nullable=True, comment='Next state'),
    sa.ForeignKeyConstraint(['issue_id'], ['sd50_issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sd11_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sd51_issue_logs')
    op.drop_table('sd61_command_device')
    op.drop_table('sd53_event_logs')
    op.drop_table('sd50_issues')
    op.drop_table('sd23_device_infos')
    op.drop_table('sd21_devices')
    op.drop_table('sd15_rel_dg_ug')
    op.drop_table('sd42_schedule_items')
    op.drop_table('sd22_device_groups')
    op.drop_table('sd16_rel_role_ug')
    op.drop_table('sd14_rel_u_ug')
    op.drop_table('sd60_command')
    op.drop_table('sd52_serial_number')
    op.drop_table('sd41_schedule_groups')
    op.drop_table('sd32_leds')
    op.drop_table('sd31_controllers')
    op.drop_table('sd19_status_privileges')
    op.drop_table('sd17_privileges')
    op.drop_table('sd13_user_groups')
    op.drop_table('sd12_codes')
    op.drop_table('sd11_users')
    op.drop_table('sd62_today_schedules')
    op.drop_table('sd30_device_models')
    op.drop_table('sd18_roles')
    op.drop_index(op.f('ix_sd10_customers_name'), table_name='sd10_customers')
    op.drop_table('sd10_customers')
    op.drop_table('sd00_blacklist_tokens')
    # ### end Alembic commands ###
