"""reset

Revision ID: 34871cab963b
Revises: 
Create Date: 2020-12-16 20:08:41.490874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34871cab963b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sd21_devices', 'dev_type',
               existing_type=sa.INTEGER(),
               comment='Device type: 0: unknown, 1: traffic light, 2: large scale devices',
               existing_comment='Device type: 0: unknown, 1: lighting',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sd30_device_models', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='Traffic Light part no',
               existing_comment='AcBel part no',
               existing_nullable=True)
    op.alter_column('sd31_controllers', 'model_id',
               existing_type=sa.INTEGER(),
               comment='Traffic Light model/part no',
               existing_comment='AcBel model/part no',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sd32_leds', 'model_id',
               existing_type=sa.INTEGER(),
               comment='Traffic Light model/part no',
               existing_comment='AcBel model/part no',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sd60_command', 'value',
               existing_type=sa.VARCHAR(length=5),
               comment='Command value, dimming = 0~100, power = 0/1 (off/on), schedule = incre (y/n)',
               existing_comment='Command value, dimming = 0~100, power = 0/1 (off/on)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sd60_command', 'value',
               existing_type=sa.VARCHAR(length=5),
               comment='Command value, dimming = 0~100, power = 0/1 (off/on)',
               existing_comment='Command value, dimming = 0~100, power = 0/1 (off/on), schedule = incre (y/n)',
               existing_nullable=False)
    op.alter_column('sd32_leds', 'model_id',
               existing_type=sa.INTEGER(),
               comment='AcBel model/part no',
               existing_comment='Traffic Light model/part no',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sd31_controllers', 'model_id',
               existing_type=sa.INTEGER(),
               comment='AcBel model/part no',
               existing_comment='Traffic Light model/part no',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sd30_device_models', 'name',
               existing_type=sa.VARCHAR(length=20),
               comment='AcBel part no',
               existing_comment='Traffic Light part no',
               existing_nullable=True)
    op.alter_column('sd21_devices', 'dev_type',
               existing_type=sa.INTEGER(),
               comment='Device type: 0: unknown, 1: lighting',
               existing_comment='Device type: 0: unknown, 1: traffic light, 2: large scale devices',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
